# https://mochajs.org/#command-line-usage
# https://github.com/mochajs/mocha/tree/master/example/config
# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml

extension:
  - ts
recursive: true
require:
  - ts-node/register # replace with ts-node/register/transpile-only if you have custom types
  - source-map-support/register
bail: false
color: true
full-trace: false
reporter: spec
spec: test/**/*.spec.ts
slow: 100
#exit: true # mocha hangs due to timeouts :(
